export const campaign = {
  campaignList: [
    {
      id: 1,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 2,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그", "인스타그램"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 3,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 4,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "뷰티"
    },
    {
      id: 5,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 6,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 7,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "패션"
    },
    {
      id: 8,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 9,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "패션"
    },
    {
      id: 10,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 11,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 12,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "인테리어"
    },
    {
      id: 13,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 14,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 15,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "기타"
    },
    {
      id: 16,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "기타"
    },
    {
      id: 17,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 18,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 19,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 20,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 21,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
    {
      id: 22,
      thumbnailUrl: "http://58.229.105.30/data/campaign/thumb/thumb-2009379591_HsYxZz32_sample_img48_300x300.png",
      snsNames: ["블로그"],
      title: "속초코다리냉면",
      description: "매콤하고~ 톡! 쏘는 맛의 코다리 냉면",
      apply: 1,
      recruits: 30,
      review: 0,
      optionList: ["구매평+리뷰", "D-Day303"],
      applicationPeriod: "04.12(월) ~ 12.01(금)",
      releaseDate: "12.02(토)",
      reviewPeriod: "12.03(일) ~ 12.07(목)",
      campaignRelease: "12.07",
      detailPageUrl: "http://58.229.105.30/img/sample_imge2.png",
      provisionDetails: "[성인 3인 제한] 동태전골 2인 + 코다리 냉면 1개 제공",
      keywords: "신사동맛집, 코다리냉면",
      notification: [
        "- 리뷰 제목에 매장명을 기재해 주시고, 매장 위치 및 지도, 연락처를 소개해 주세요",
        "- 매장 인테리어 및 제공받으신 서비스를 15장 이상 , 동영상(15초 이상)을 촬영해주세요",
        "(촬영시 타인의 초상권문제가 있을수 있으니 타인의 얼굴이 노출되지 않도록 참고 부탁드립니다.)"
      ],
      notificationAdd: "초과비용 본인 부담 / 타쿠폰 중복적용 불가 / 핸드폰카메라 촬영불가 / 테이크 아웃 불가",
      category: "식품"
    },
  ]
}

export const menu = {
  mainMenu: ["구매평", "구매평 + 리뷰"],
  subMenu: ["전체", "식품", "생활", "뷰티", "패션", "유아동", "반려동물", "디지털", "운동/건강", "레저/스포츠", "인테리어", "기타"]
}
